extends SceneTree

func _init() -> void:
    var script = load("res://scripts/news_system.gd")
    assert(script != null, "NewsSystem script must load")
    var news = script.new()
    root.add_child(news)
    assert(news.SECTIONS.size() == 10, "RENEW Daily must expose all ten sections")
    assert(news.SECTIONS.has("Your Company"), "Company section missing")
    assert(news.SECTIONS.has("People"), "People section missing")
    assert(news.SECTIONS.has("Market"), "Market section missing")
    assert(news.SECTIONS.has("Rivals"), "Rivals section missing")
    assert(news.SECTIONS.has("Supply Chain"), "Supply Chain section missing")
    assert(news.SECTIONS.has("Contracts"), "Contracts section missing")
    assert(news.SECTIONS.has("Opportunities"), "Opportunities section missing")
    assert(news.SECTIONS.has("Regions"), "Regions section missing")
    assert(news.SECTIONS.has("World"), "World section missing")
    assert(news.SECTIONS.has("Corporate History"), "Corporate History section missing")
    var snapshot: Dictionary = news.capture_state()
    assert(snapshot.has("archive"), "News archive must be persisted")
    assert(snapshot.has("current_issue"), "Current newspaper must be persisted")
    news.restore_state(snapshot)
    assert(news.get_archive(10) is Array, "News archive API must return an array")
    print("NEWS SYSTEM TESTS PASSED")
    quit()
