extends Node

## Runtime bridge for the responsive mobile command grid.
##
## The mobile HUD mirrors desktop action buttons. The desktop buttons already
## own the authoritative gameplay callbacks, so mobile buttons must proxy the
## desktop button's `pressed` signal instead of trying to reconstruct a bound
## Callable from Signal.get_connections().
##
## This also makes the bridge resilient to `_refresh()` rebuilding the action
## grid: newly-created mobile buttons are repaired automatically.

var _wired: Dictionary = {}

func _process(_delta: float) -> void:
    var hud := get_tree().root.get_node_or_null("Renew/UI/MainHUD")
    if hud == null:
        return
    var mobile_actions: Node = hud.get("mobile_actions")
    var action_grid: Node = hud.get("action_grid")
    if mobile_actions == null or action_grid == null:
        return

    var sources: Dictionary = {}
    for child in action_grid.get_children():
        if child is Button:
            sources[String(child.text)] = child

    var live_buttons: Dictionary = {}
    for child in mobile_actions.get_children():
        if not child is Button:
            continue
        var button := child as Button
        var source: Button = sources.get(String(button.text)) as Button
        if source == null:
            continue
        live_buttons[button] = true
        var previous: Variant = _wired.get(button)
        if previous == source:
            button.custom_minimum_size.y = maxf(button.custom_minimum_size.y, 46.0)
            continue

        # These mobile buttons are generated by renew_sims_ui.gd and may carry
        # its legacy/broken callback. Remove those connections before installing
        # the authoritative desktop-action proxy.
        for connection in button.pressed.get_connections():
            var callable: Callable = connection.get("callable", Callable())
            if callable.is_valid():
                button.pressed.disconnect(callable)
        button.pressed.connect(_proxy_pressed.bind(source))
        button.custom_minimum_size.y = maxf(button.custom_minimum_size.y, 46.0)
        _wired[button] = source

    for button in _wired.keys():
        if not is_instance_valid(button) or not live_buttons.has(button):
            _wired.erase(button)

func _proxy_pressed(source: Button) -> void:
    if source == null or not is_instance_valid(source) or not source.visible:
        return
    source.emit_signal("pressed")
